// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVV1pwkdvwo0sOoudOtaSeU8XgQoONJY',
    appId: '1:532159564212:ios:79a8a4dadbfb2e0e104ae1',
    messagingSenderId: '532159564212',
    projectId: 'local-lens-82877',
    storageBucket: 'local-lens-82877.firebasestorage.app',
    iosBundleId: 'com.example.locallens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYVV1pwkdvwo0sOoudOtaSeU8XgQoONJY',
    appId: '1:532159564212:ios:79a8a4dadbfb2e0e104ae1',
    messagingSenderId: '532159564212',
    projectId: 'local-lens-82877',
    storageBucket: 'local-lens-82877.firebasestorage.app',
    iosBundleId: 'com.example.locallens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHXdFR8eAL5Mgzf-j8G0V9tl1vZzh2Ey8',
    appId: '1:532159564212:web:845cf7bd3d7fda35104ae1',
    messagingSenderId: '532159564212',
    projectId: 'local-lens-82877',
    authDomain: 'local-lens-82877.firebaseapp.com',
    storageBucket: 'local-lens-82877.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXdFR8eAL5Mgzf-j8G0V9tl1vZzh2Ey8',
    appId: '1:532159564212:web:845cf7bd3d7fda35104ae1',
    messagingSenderId: '532159564212',
    projectId: 'local-lens-82877',
    authDomain: 'local-lens-82877.firebaseapp.com',
    storageBucket: 'local-lens-82877.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqeJJYOrlCUys9MHR92W_dqtq8f3YQcQ',
    appId: '1:532159564212:android:0500339b91df770f104ae1',
    messagingSenderId: '532159564212',
    projectId: 'local-lens-82877',
    storageBucket: 'local-lens-82877.firebasestorage.app',
  );
}
